apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  type: NodePort
  selector:
    app: couchbase
  ports:
    - name: admin-console
      port: 8091
      nodePort: 30016
    - name: query-serviuce
      port: 8092
      nodePort: 30017
    - name: index-service
      port: 8093
      nodePort: 30018
    - name: full-text-search
      port: 8094
      nodePort: 30019
    - name: data-service
      port: 11210
      nodePort: 30020
    

      