apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-app
spec:
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
      - name: couchbase-container
        image: couchbase:community
        ports:
          - containerPort: 8091
          - containerPort: 8092
          - containerPort: 8093
          - containerPort: 8094
          - containerPort: 11210
        env:
        - name: COUCHBASE_ADMINISTRATOR_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchbase-secret
              key: username

        - name: COUCHBASE_ADMINISTRATOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchbase-secret
              key: password


